### ISSUE TITLE
Camera not working properly in iPod Touch 5th Gen

### ISSUE THREAD

**Issue by faizmokhtar** [danielebogo/DBCamera#106]
I am currently testing my project on iPod Touch 5th Gen running iOS 8.1 and it seems the camera doesn't work properly. Even the front camera does not work. It only displays a black screen as screenshot below. 
![img_0034](https://cloud.githubusercontent.com/assets/1093100/4767477/0a5e5b4c-5b5e-11e4-886d-268c4eb43ecd.PNG)

When displaying the view, the logs shows the following error:
````
[PLLogging] ***** Error: logging directory does not exist /var/mobile/Library/Logs/CrashReporter/DiagnosticLogs/
[PLLogging] ***** Error: logging directory does not exist /var/mobile/Library/Logs/CrashReporter/DiagnosticLogs/
````
And when pressing the capture button, the logs shows the following and finally crashed.
````
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureStillImageOutput captureStillImageAsynchronouslyFromConnection:completionHandler:] - inactive/invalid connection passed.'
````
Then, I add an exception to check where's the problem at.
![screen shot 2014-10-24 at 4 36 40 pm](https://cloud.githubusercontent.com/assets/1093100/4767513/e875c2e4-5b5e-11e4-9d45-24204bbf90d6.png)

By the way, the iPod that I use only have a front camera available. It seems to work fine when I test it on device that have both front and back camera. :confused:

**Comment by danielebogo** [comment]
Fix it

**Comment by faizmokhtar** [comment]
Kudos! :thumbsup:

**Comment by xiekunRonaldo** [comment]
The problem still exists in ipod touch 5th ,8.1.2

**Comment by jerry-sl** [comment]
@danielebogo Could you please give some more detail about how this issue fixed? I recently get a crash 

Fatal Exception: NSInternalInconsistencyException
*** -[AVCaptureStillImageOutput captureStillImageAsynchronouslyFromConnection:completionHandler:] - inconsistent state.

**Comment by sciutand** [comment]
I get many of these errors too.
