### ISSUE TITLE
CameraContainer instantly dealloc-ing

### ISSUE THREAD

**Issue by pjebs** [danielebogo/DBCamera#108]
I have a subclassed UINavigationController (= 'self'). My camaraContainer seems to dealloc immediately. Other than that, everything seems to work perfectly. (i.e. CameraViewController etc works perfectly). Is this expected behaviour?
- (void)viewDidLoad
{
    //Create CameraController
    DBCameraViewController *cameraController = [DBCameraViewController initWithDelegate:self];
    [cameraController setUseCameraSegue:NO];
    
    DBCameraContainerViewController *cameraContainer = [[DBCameraContainerViewController alloc] initWithDelegate:self];
    [cameraContainer setCameraViewController:cameraController];
    
    [self setNavigationBarHidden:YES];
    [self setViewControllers:@[cameraContainer]];
}

**Comment by danielebogo** [comment]
fix it. i'm going to push this fix. Thanks.
