### ISSUE TITLE
Frontal camera

### ISSUE THREAD

**Issue by nab0y4enko** [danielebogo/DBCamera#120]
How can I set the camera when creating DBCameraViewController?

```
DBCameraViewController *cameraViewController = [DBCameraViewController initWithDelegate:self];
cameraViewController.forceQuadCrop = YES;

UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:imagePickerViewController];
navigationController.navigationBarHidden = YES;
[self presentViewController:navigationController animated:YES completion:nil];
```

**Comment by jstrocel** [comment]
I created a workaround with the custom camera function. You can see the full implementation in my fork at https://github.com/jstrocel/Cordova-DBCamera. I hope it helps!
 
    [self.viewController presentViewController:nav animated:YES completion:^(){
        if (cameraDirection == true){
          [camera.delegate switchCamera];
        }
    }];

**Comment by LadyDeveloper** [comment]
Hi! I use your library! It's awesome!
I present camera controller in navigation controller with push method, but 
[camera.delegate switchCamera]; 
after or before pushViewController, not working.
How could I do?
