### ISSUE TITLE
Square Images?

### ISSUE THREAD

**Issue by Steven4294** [danielebogo/DBCamera#121]
Is there a way to generate square images with this library? I am using the camera in conjunction with another image editing SDK, and I would like the camera to be forcing a square image in the user interface to start out with, not forcing a square image after the picture has already been taking (which can be done with quad force).

**Comment by tomisacat** [comment]
I came to the same requirement. Is there anyway to force quad in DBCameraViewController but not DBCameraSegueViewController after photo already taken with modify source code in Pod?

**Comment by danielebogo** [comment]
Hi guys, the possibility to set the camera in square format, is going to be implemented in the new version (with iPad layout)

**Comment by Steven4294** [comment]
Hi Daniel, thanks for the reply that it is great to hear. Is there any timeline we could expect to see for the new version?

**Comment by Steven4294** [comment]
@tomisacat One work around I've used is to force crop the image in the image did dismiss method (using another image Cropping library), and then just add black subviews to the camera view controller so that the visible cameraView is square. This is very hack, but it seems to get the job done.

**Comment by danielebogo** [comment]
@tomisacat could be a solution. Good walk around.
I don't have a deadline because i've different projects to complete. I would to complete the new layout before start the development. I'll upload all in a new branch and you can test it, give me some feedback etc.... before merge it on master.

**Comment by Steven4294** [comment]
@danielebogo That sounds great, I'd be happy to test it

**Comment by tomisacat** [comment]
@Steven4294 Thanks for the solution!
@danielebogo Appreciate your great work!
