### ISSUE TITLE
Change Filter Stock Image 

### ISSUE THREAD

**Issue by manikkalra** [danielebogo/DBCamera#123]
I was wondering if it's possible to change the stock image of the lady that appears in all filters to our own custom image ?

**Comment by Steven4294** [comment]
You could always just find a new asset for each image, it wouldn't be that hard

**Comment by danielebogo** [comment]
@Steven4294 let me some minutes to upload this fix... now you will see the thumb of your captured image with filter applied instead of the lady

**Comment by danielebogo** [comment]
ok, check the last commit on master or the version 2.3.9 on Cocoapods

**Comment by manikkalra** [comment]
Thanks you :)
