### ISSUE TITLE
Skip segue

### ISSUE THREAD

**Issue by larssondaniel** [danielebogo/DBCamera#124]
Is it possible to skip the filter/crop view that is pushed after taking a photo? I want 

`- (void) camera:(id)cameraViewController didFinishWithImage:(UIImage *)image withMetadata:(NSDictionary *)metadata`

to be called as soon as I have taken a photo or chosen one from the library.

**Comment by danielebogo** [comment]
@larssondaniel use this ```DBCameraViewController``` property ```@property (nonatomic, assign) BOOL useCameraSegue;``` to skip the filter/crop.
