### ISSUE TITLE
"inactive/invalid connection" crashing app

### ISSUE THREAD

**Issue by kraftydevil** [danielebogo/DBCamera#125]
The full crash message:

Reason: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureStillImageOutput captureStillImageAsynchronouslyFromConnection:completionHandler:] - inactive/invalid connection passed.'

![screen shot 2015-01-10 at 6 03 54 pm](https://cloud.githubusercontent.com/assets/1315619/5693633/527dc11a-98f3-11e4-8e0e-614fc4525e09.png)
I've got about 60 total crashes spanning just about every device that can run iOS 8.

Am I using the library incorrectly?

Attaching a screenshot of my code:
![screen shot 2015-01-10 at 6 02 50 pm](https://cloud.githubusercontent.com/assets/1315619/5693636/6fa51eaa-98f3-11e4-8c54-7a14c073f9ed.png)

**Comment by danielebogo** [comment]
Hi @kraftydevil ,
try the last commit on master. I don't know if the problem is on the connection or on the output format.
Do you know if the problem appears on a specific device? Like iPod or iPad?

**Comment by kraftydevil** [comment]
Is master different from version 2.3.9? I am using cocoapods. Do I need to integrate differently to test any updates?

Most of the crashes have come from iPhones 6, 6+, 5, 5s, 5c, and 4s.

There was at least one crash from an iPad 4th generation but that's not the bulk case.

**Comment by danielebogo** [comment]
@kraftydevil yes, i've changed the method that creates the Connection. But i don't know if it is the problem.

**Comment by kraftydevil** [comment]
@danielebogo Can you point me in the right direction regarding how to use cocoapods to pull from master?

**Comment by danielebogo** [comment]
@kraftydevil take a look: http://guides.cocoapods.org/using/the-podfile.html

Something like this:
pod 'DBCamera', :git => 'https://github.com/danielebogo/DBCamera.git'

**Comment by kraftydevil** [comment]
I've been able to reproduce the problem by disabling the camera for my app. Settings > Privacy > Camera > Toggle app.

I believe this is an iOS 8 thing: http://stackoverflow.com/questions/26070393/is-there-a-way-to-ask-user-for-camera-access-after-they-have-already-denied-it-o

Is this something you addressed in master?

**Comment by danielebogo** [comment]
@kraftydevil the library don't check the auth state of the camera, but could be a plus to implement int the next version.
Check this if you want to display to the user how he can activate the privacy: [DBPrivacyHelper](https://github.com/danielebogo/DBPrivacyHelper)
