### ISSUE TITLE
How do you you start the camera in front facing mode?

### ISSUE THREAD

**Issue by nikilster** [danielebogo/DBCamera#126]
Thanks for creating this sweet library! I've been trying to figure out how to start the camera in front facing mode - like 

``` picker.cameraDevice = UIImagePickerControllerCameraDeviceFront ```

in ```UIImagePickerController```.

Whats the best way to do this?

**Comment by danielebogo** [comment]
Hi @nikilster , i need to implement this feature. I close this issue and move it at #120
