### ISSUE TITLE
How to automatically adjust Exposure when tap screen to focus that point?

### ISSUE THREAD

**Issue by tomisacat** [danielebogo/DBCamera#127]
Like Instagram, when user tap the screen it will automatically adjust exposure(Intuitively, the brightness of screen changed), Or, like Camera.app, user could swipe up and down to adjust the exposure. I set cameraController.cameraManager.exposureMode = AVCaptureExposureModeContinuousAutoExposure; but it can't meet my requirement. So which property should be set or what function should be called to enable automatically adjust exposure?

**Comment by danielebogo** [comment]
Hi @tomisacat the spouse should be AVCaptureExposureModeContinuousAutoExposure by default.
If you tap one time you set the focus point and if you tap 2 times, you set the exposure point.

**Comment by tomisacat** [comment]
But user cannot adjust the exposure value by double tap. For Camera.app, user could swipe up and down to adjust exposure value after tap the screen and get a new focus point, I don't need accurately adjust the exposure value but automatically adjust it once upon user tap the screen, Is it possible to do it, just like Instagram?

**Comment by danielebogo** [comment]
The DBCamera has only the possibility to set the exposure by double tap (when you see the green circle as default) and the screen change brightness automatically.

**Comment by tomisacat** [comment]
When I double tap screen it didn't change brightness(or maybe the value changed scarcely which I could not feel), But Instagram could feel the change, it made me thought that it didn't change. I'll test more,thank you!
