### ISSUE TITLE
Struggling to get DBCamera working with IOS 8.1 and Swift

### ISSUE THREAD

**Issue by neonrazor** [danielebogo/DBCamera#128]
I have followed the instructions for adding as a library.a file and as a framework and neither work for me, I get cannot find the GPUImage.h which when I add the path of the framework to the header search path I get duplicate definition warnings.

Is there anyway you can help me as I am pulling my hair out with this and really do not want to have to write my own camera interface.

**Comment by danielebogo** [comment]
Hi @neonrazor i think the problem is this: #111 
This because i've started this library before Swift.

**Comment by neonrazor** [comment]
Thanks for the prompt reply, have you any plans to convert it to Swift and what would the timescales be?

Date: Fri, 16 Jan 2015 00:56:21 -0800

**Comment by danielebogo** [comment]
@neonrazor my idea is to do a big refactor, with a new layout, new iOS target, clean code. Use auto layout and replace GPUImage with Core image filter (available on iOS 7 and 8). After this i could start with Swift, but i don't know when.

**Comment by NitWitStudios** [comment]
@danielebogo Bump! Trying to get it to work in Swift as well, any chance you can make it compatible with cocoa pods 'use_frameworks!'?

Thanks!
