### ISSUE TITLE
Could you please add russian localization

### ISSUE THREAD

**Issue by kronik** [danielebogo/DBCamera#129]
Could you please add russian localization:

"button.use" = "Использовать";
"button.retake" = "Переснять";

"general.error.title" = "Внимание";
"general.button.cancel" = "Отмена";

"pickerimage.nopolicy" = "Пожалуйста, разрешите доступ для доступа к вашей Фото Библиотеке. Проверить параметры доступа можно в Настройки > Конфиденциальность > Фотографии";

"pagecontrol.text" = "%i из %i";

"cropmode.title" = "Соотношение сторон";
"cropmode.square" = "Квадрат";

**Comment by pjebs** [comment]
fork it(top right button), make the changes and then do a pull-request. It's easier for @danielebogo

**Comment by danielebogo** [comment]
check the last commit on master. It should be added.

**Comment by kronik** [comment]
Thanks!
