### ISSUE TITLE
Orientation Issues with iPad

### ISSUE THREAD

**Issue by JontyC** [danielebogo/DBCamera#131]
Using a brand new iPad project, and the demo code as below:

```objective-c
- (void) openCamera
{
    DBCameraContainerViewController *cameraContainer = [[DBCameraContainerViewController alloc] initWithDelegate:self];
    [cameraContainer setFullScreenMode];

    UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:cameraContainer];
    [nav setNavigationBarHidden:YES];
    [self presentViewController:nav animated:YES completion:nil];
}

```
When the device in portrait (right way up), it works fine, but any other orientation, the camera isn't at the correct angle, and rotating the device fails to fix the issue. 

Reproducible on iPad 2, iPad Mini 1st Gen, Retina iPad Mini etc.

**Comment by danielebogo** [comment]
Hi @JontyC this because (as the default camera) the controller must be portrait and the library set the orientation in background using the accelerometer. You can look the system camera and see that change the disposition / rotation of the buttons, but the controller don't rotate. (check #113 )
