### ISSUE TITLE
AssetURL of images from Library are missing.

### ISSUE THREAD

**Issue by fran-sgd** [danielebogo/DBCamera#137]
Apple's UIImagePickerController will return a dictionary of asset information in the didFinishPickingMediaWithInfo method. This allows discovering the URL of the image with the UIImagePickerControllerReferenceURL constant key. 

How do I find the same information when using the built in image picker on this Camera view? I've dug through the metadata when the source is 'Library' and can't seem to find that URL nor the info dictionary. 

The issue for my app is that I do a series of expensive image manipulations and use the URL as an identifier since it contains a UUID. This gives the opportunity to cache expensive versions of images efficiently. Also, the app allows sharing and being able to check the UUID of the image will tell me if I have the image in the library or in memory already instead of moving it over the network.

It looks like the library collection uses this information but doesn't pass it on upon image selection, is there an easy way to get it and pass it on?

**Comment by danielebogo** [comment]
Hi @fran-sgd i can add the defaultRepresentation url as parameter within the metadata dictionary

**Comment by danielebogo** [comment]
Something like this:
```DBCameraAssetURL = "assets-library://asset/asset.JPG?id=045D177F-D818-4C86-8BDD-8D81ECA4159A&ext=JPG";```

**Comment by fran-sgd** [comment]
Oh, Thanks! That would certainly help me, and I'm sure you'd be able to change the code much faster that I can trace through it to find it. :-)

**Comment by danielebogo** [comment]
Later it's easy to retrieve the asset using ```- (void)assetForURL:(NSURL *)assetURL resultBlock:(ALAssetsLibraryAssetForURLResultBlock)resultBlock failureBlock:(ALAssetsLibraryAccessFailureBlock)failureBlock;``` method of ```ALAssetsLibrary``` class

**Comment by danielebogo** [comment]
let me a second to commit this change and you can try it

**Comment by danielebogo** [comment]
@fran-sgd it's on master

**Comment by danielebogo** [comment]
ref: https://github.com/danielebogo/DBCamera/commit/e9f914655307beef2e6ec2b0f677d68d42a07650

**Comment by fran-sgd** [comment]
Beautiful, works perfectly!

Thanks for the update, this is a excellent camera component. I can't think of a reason to use anything else since you've covered everything so well. Great work!

**Comment by danielebogo** [comment]
Thanks a lot @fran-sgd !!!
