### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by confile** [danielebogo/DBCamera#143]
I get the following error when compiling the example app: 

![dbcamera_xcodeproj](https://cloud.githubusercontent.com/assets/64265/6592630/d047c756-c7d0-11e4-9cd9-dc5286acfd4a.png)

**Comment by danielebogo** [comment]
Hi @confile , did you run pod install and open DBCamera.xcworkspace?

**Comment by confile** [comment]
sorry I missed that. Thanks for help.
