### ISSUE TITLE
#172 breaks usage with use_frameworks

### ISSUE THREAD

**Issue by mkoppanen** [danielebogo/DBCamera#177]
Seems like the PR #172 breaks usage with CocoaPods use_frameworks. Similar issue:

https://github.com/CocoaPods/CocoaPods/issues/3226

"Those Pods will need to be updated to use bundleForClass: instead of mainBundle, so that they work as both framework and static library."

**Comment by leobarrospereira** [comment]
Pull request to fix this:
https://github.com/danielebogo/DBCamera/pull/178

**Comment by danielebogo** [comment]
Merged, tag 2.4.1 created and podspec pushed to cocoapods! Thanks guys!
